### ISSUE TITLE
Are there any command for reset or jump to a address to run?

### ISSUE THREAD

**Issue by jswyll** [Wiz-IO/Mediatek-MT2625-Flash-Utility#1]
Are there any command for reset or jump to a address to run? I want to reboot the chip or jump to application automatically after download application.

**Comment by Wiz-IO** [comment]
edit:
https://github.com/Wiz-IO/wizio-gsm/blob/main/builder/frameworks/MT6261.py#L363

use this file - the bugs are fixed

**Comment by jswyll** [comment]
It is quite useful, thank you very much!
